# example values
indexing-settings:
  user-agent: HeliontSearchBot
  referrer: https://www.google.com
  crawl-delay-ms: 1000
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
    - url: http://lib.ru
      name: Lib
    - url: https://www.svetlovka.ru
      name: Svetlovka

server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&serverTimezone=UTC
    username: root
    password: Mysqlurmat1970$
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog2.yaml